default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_general_ci
  host: <%= ENV['JAWSDB_HOST'] %>
  port: <%= ENV['JAWSDB_PORT'] %>
  # Change these credentials to match your own environment
  username: <%= ENV['JAWSDB_USER'] %>
  password: <%= ENV['JAWSDB_PASSWORD'] %>

development:
  <<: *default
  database: qpixel_dev

test:
  <<: *default
  database: qpixel_test

production:
  <<: *default
  database: <%= ENV['JAWSDB_DATABASE'] %>

redis_default: &redis_default
  host: <%= ENV['REDIS_HOST'] %>
  port: <%= ENV['REDIS_PORT'] %>
  password: <%= ENV['REDIS_PASSWORD'] %>
  db: 0
  # Also supported: db, url, path, password. See https://github.com/redis/redis-rb for docs.

redis_development:
  <<: *redis_default

redis_test:
  <<: *redis_default

redis_production:
  # If you want to use a shared Redis server in prod (for load-balanced servers or whatever else),
  # change this to those settings.
  <<: *redis_default
