test:
  service: Disk
  root: <%= Rails.root.join('tmp/storage') %>

local:
  storage: Disk
  root: <%= Rails.root.join('storage') %>

s3:
  service: S3
  access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
  region: ap-southeast-1
  bucket: <%= ENV['AWS_BUCKET'] %>
